import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const bricolageGrotesque = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricolageGrotesque.className}>{children}</body>
    </html>
  );
}

// import { cn } from "@/lib/utils";
// import type { Metadata } from "next";
// import {
//   Bricolage_Grotesque,
//   Bricolage_Grotesque as FontSans,
// } from "next/font/google";
// import "./globals.css";

// const bricolageGrotesque = Bricolage_Grotesque({ subsets: ["latin"] });

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={
//           (bricolageGrotesque.className,
//           cn(
//             "min-h-screen antialiased"

//             // fontSans.variable
//           ))
//         }
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
